### ISSUE TITLE
Crash everytime i go throug portal:/

### ISSUE THREAD

**Issue by mexxtm** [ganymedes01/TheErebus#360]
Hi. I have a problem. . My Minecrafy crash everytime i go to the portal:/ this is my crash report:

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 18.10.15 15:38
Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException: 32895
	at net.minecraft.world.biome.BiomeGenBase.func_150560_b(BiomeGenBase.java:390)
	at net.minecraft.world.biome.BiomeGenBase.func_150573_a(BiomeGenBase.java:365)
	at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_219_WorldEventHandler_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at erebus.world.ChunkProviderErebus.replaceBlocksForBiome(ChunkProviderErebus.java:272)
	at erebus.world.ChunkProviderErebus.func_73154_d(ChunkProviderErebus.java:148)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at erebus.world.teleporter.TeleporterErebus.func_77184_b(TeleporterErebus.java:58)
	at erebus.world.teleporter.TeleporterErebus.func_77185_a(TeleporterErebus.java:28)
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at erebus.world.teleporter.TeleporterHandler.transferEntity(TeleporterHandler.java:99)
	at erebus.world.teleporter.TeleporterHandler.transferToErebus(TeleporterHandler.java:36)
	at erebus.block.ErebusPortal.func_149670_a(ErebusPortal.java:105)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeGenBase.func_150560_b(BiomeGenBase.java:390)
	at net.minecraft.world.biome.BiomeGenBase.func_150573_a(BiomeGenBase.java:365)
	at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_219_WorldEventHandler_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at erebus.world.ChunkProviderErebus.replaceBlocksForBiome(ChunkProviderErebus.java:272)
	at erebus.world.ChunkProviderErebus.func_73154_d(ChunkProviderErebus.java:148)

-- Chunk to be generated --
Details:
	Location: -34,-68
	Position hash: -287762808866
	Generator: ErebusRandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-539,127,-1087), Chunk: (at 5,7,1 in -34,-68; contains blocks -544,0,-1088 to -529,255,-1073), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at erebus.world.teleporter.TeleporterErebus.func_77184_b(TeleporterErebus.java:58)
	at erebus.world.teleporter.TeleporterErebus.func_77185_a(TeleporterErebus.java:28)
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at erebus.world.teleporter.TeleporterHandler.transferEntity(TeleporterHandler.java:99)
	at erebus.world.teleporter.TeleporterHandler.transferToErebus(TeleporterHandler.java:36)
	at erebus.block.ErebusPortal.func_149670_a(ErebusPortal.java:105)

-- Block being collided with --
Details:
	Block type: ID #2102 (tile.erebus.portal // erebus.block.ErebusPortal)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-508,90,-1057), Chunk: (at 4,5,15 in -32,-67; contains blocks -512,0,-1072 to -497,255,-1057), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)

-- Entity being checked for collision --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 3996
	Entity Name: Mexx
	Entity's Exact location: -507,00, 90,00, -1055,00
	Entity's Block location: World: (-507,90,-1055), Chunk: (at 5,5,1 in -32,-66; contains blocks -512,0,-1056 to -497,255,-1041), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3b0be238
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 216209920 bytes (206 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 11, tcache: 8847, allocated: 1, tallocated: 18
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_C1 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.11} [BuildCraft] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.11} [BC Builders] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.11} [BC Transport] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.11} [BC Energy] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.11} [BC Silicon] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.11} [BC Robotics] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.11} [BC Factory] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EE3{0.3.501} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.501.jar) 
	UCHIJAAAA	exnihilo{1.38-48} [Ex Nihilo] (Ex-Nihilo-1.38-48.jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.3.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	llor{1.0.3-mc1.7.10} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.3-mc1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.9} [MalisisCore] (malisiscore-1.7.10-0.12.9.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.10} [Malisis' Doors] (malisisdoors-1.7.10-1.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	millenaire{6.0.0} [MillĂ©naire] (millenaire-6.0.0.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC3-84.jar) 
	UCHIJAAAA	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	erebus{0.3a} [Erebus] (TheErebus-0.3a.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
	UCHIJAAAA	TWarden{1.1.1} [Thaumic Warden] (TWarden-1.1.1.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.0-102
	TConstruct Environment: Environment healthy.
	NetherOres: Lacking version information.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Mexx'/3996, l='LastEarth', x=-507,00, y=90,00, z=-1055,00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Do you have idea what can I do?

**Comment by vadis365** [comment]
Probably Mariculture see #340
