### ISSUE TITLE
Problem with Galacticcraft

### ISSUE THREAD

**Issue by SugarDaddii** [ganymedes01/TheErebus#471]
HEY this problem pop up when i teleport to Erebus world

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 01.02.16 00:22
Description: Exception generating new chunk

java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.asteroids.world.gen.BiomeGenBaseAsteroids cannot be cast to erebus.world.biomes.BiomeBaseErebus
	at erebus.world.genlayer.GenLayerSubBiomes.func_75904_a(GenLayerSubBiomes.java:35)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:23)
	at erebus.world.WorldChunkManagerErebus.func_76931_a(WorldChunkManagerErebus.java:88)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76839_e(SourceFile:87)
	at erebus.world.WorldChunkManagerErebus.func_76931_a(WorldChunkManagerErebus.java:84)
	at erebus.world.WorldChunkManagerErebus.func_76933_b(WorldChunkManagerErebus.java:73)
	at erebus.world.ChunkProviderErebus.func_73154_d(ChunkProviderErebus.java:145)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at erebus.world.teleporter.TeleporterErebus.func_77184_b(TeleporterErebus.java:58)
	at erebus.world.teleporter.TeleporterErebus.func_77185_a(TeleporterErebus.java:28)
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at erebus.world.teleporter.TeleporterHandler.transferEntity(TeleporterHandler.java:99)
	at erebus.world.teleporter.TeleporterHandler.transferToErebus(TeleporterHandler.java:36)
	at erebus.block.ErebusPortal.func_149670_a(ErebusPortal.java:105)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:57)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by vadis365** [comment]
Duplicate issue of this #243
Not our fault - please follow the link to Galacticraft's issues.
