### ISSUE TITLE
Erebus - Already decorating crash

### ISSUE THREAD

**Issue by Killgrave** [ganymedes01/TheErebus#500]
```
java.lang.RuntimeException: Already decorating Erebus!
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:766)
	at net.minecraft.world.World.func_147439_a(World.java:692)
	at net.minecraft.world.World.func_98179_a(World.java:3675)
	at net.minecraft.world.World.updateLightByType(World.java:3806)
	at net.minecraft.world.World.func_147463_c(World.java:4879)
	at net.minecraft.world.World.func_147451_t(World.java:3663)
	at net.minecraft.world.World.func_147465_d(World.java:842)
	at net.minecraft.world.World.func_147449_b(World.java:996)
	at erebus.world.feature.decoration.WorldGenRedGem.func_76484_a(WorldGenRedGem.java:34)
	at erebus.world.biomes.decorators.BiomeDecoratorSubmergedSwamp.generateFeature(BiomeDecoratorSubmergedSwamp.java:272)
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:45)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:766)
	at net.minecraft.world.World.func_147439_a(World.java:692)
	at erebus.world.SpawnerErebus.runGradualSpawning(SpawnerErebus.java:160)
	at erebus.world.SpawnerErebus.onServerTick(SpawnerErebus.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_97_SpawnerErebus_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
```
```
java.lang.RuntimeException: Already decorating Erebus!
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
```

Erebus 0.4.5
Thermos 44 
Forge 1614

**Comment by ProsperCraft** [comment]
We are having the same problem on our dedicated server.

http://pastebin.com/B688a8am
http://pastebin.com/xBifA25n
http://pastebin.com/TPmBvHqc
http://pastebin.com/AgAhpCGr
http://pastebin.com/MSPc9BDW
http://pastebin.com/f5jfqU9w
http://pastebin.com/Nv868nJR
http://pastebin.com/pH5Biehj

Hopefully one of those will help, I saw something about a red gem in there.

**Comment by vadis365** [comment]
Hello,

Thanks guys for the bug reports.
I have spoken to @chylex, who originally made The Erebus worldgen code and he has advised me as to why this is happening. Would it be possible to supply me a world seed and if possible co-ordinates - apparently this issue will occur always on the same seed. It would make my testing and fix of this bug a lot easier. I am hoping to get a new 1.7.10 (possibly the last until the 1.9 port) update out in the next week or 2 depending on time available. Sorry about the problems. This WILL be sorted :)

Cheers,
Me.

**Comment by ProsperCraft** [comment]
Seed: 7337065745325800828  

The locations are in the crash reports.

**Comment by vadis365** [comment]
I have added a check for the redgem to make sure it will only place blocks in chunks that exist.
Using the above seed and co-ords from the crash report I have no crashes.
Going to close for now - but will open again if it happens in the future.

**Comment by Davoleo** [comment]
Having the same problem on a project ozone 2 server 
https://pastebin.com/p0qjfahM

This happens when people explore The Erebus
