### ISSUE TITLE
The game Crashes when i use the wand of Animation 

### ISSUE THREAD

**Issue by Ryius** [ganymedes01/TheErebus#521]
java.lang.NullPointerException: Ticking memory connection
    at erebus.entity.EntityMobBlock.func_110147_ax(EntityMobBlock.java:99)
    at erebus.entity.EntityAnimatedBlock.func_110147_ax(EntityAnimatedBlock.java:75)
    at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:120)
    at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91)
    at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
    at erebus.entity.EntityMobBlock.<init>(EntityMobBlock.java:18)
    at erebus.entity.EntityAnimatedBlock.<init>(EntityAnimatedBlock.java:48)
    at erebus.item.ItemWandOfAnimation.func_77648_a(ItemWandOfAnimation.java:61)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Ryius** [comment]
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at erebus.entity.EntityMobBlock.func_110147_ax(EntityMobBlock.java:99)
    at erebus.entity.EntityAnimatedBlock.func_110147_ax(EntityAnimatedBlock.java:75)
    at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:120)
    at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91)
    at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
    at erebus.entity.EntityMobBlock.<init>(EntityMobBlock.java:18)
    at erebus.entity.EntityAnimatedBlock.<init>(EntityAnimatedBlock.java:48)
    at erebus.item.ItemWandOfAnimation.func_77648_a(ItemWandOfAnimation.java:61)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

**Comment by vadis365** [comment]
Hello,
The crash you are getting looks like it is to do with the mob attack damage multiplier settings added to the latest version. I think the attribute is being set twice and to 2 different values which looks like a derp on my behalf - sorry about that. I'll see if I can duplicate this issue and fix it.
Cheers,
Me.

**Comment by Ryius** [comment]
jop no poblemo

**Comment by Ryius** [comment]
can you say me when the new v is out

**Comment by vadis365** [comment]
Bug fix is released and under review on curse so it should be up soon.
@Darkosto should know about this - so flagging him here :)

**Comment by Ryius** [comment]
thanks
