### ISSUE TITLE
[1.12.2] Client is crashing upon trying to use Minecraft's integrated Recipe Book, kicked an error on the paxel recipe

### ISSUE THREAD

**Issue by Psyscicyclic** [ganymedes01/TheErebus#585]
[1.12.2] Client is crashing upon trying to use Minecraft's integrated Recipe Book, kicked an error on the paxel recipe.

---
Forge 14.23.2.2624 (forge-1.12.2-14.23.2.2624-universal.jar)
Erebus 1.0.21 (Erebus-1.0.21.jar)

Relevant excerpts from crash report:

java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: erebus.recipes.RecipePaxel@265d2725 Name: erebus:recipe_paxel
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	atnet.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_146284_a(SourceFile:113)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_73864_a(SourceFile:101)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_146284_a(SourceFile:113)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_73864_a(SourceFile:101)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

**Comment by vadis365** [comment]
Hello,
I have tested both recipes for the paxel and they work for me using the MC book. I'm not sure what is happening for you here. Could you post a list of the mods you are using so I can debug any possible mod interactions?
Cheers,
Me.

**Comment by vadis365** [comment]
![paxel](https://user-images.githubusercontent.com/6518708/37628138-0599b8ae-2bd0-11e8-96c7-d9c3e83ba024.gif)
