### ISSUE TITLE
[1.12.2]Crushroom sporeball causes server crash

### ISSUE THREAD

**Issue by drstasis** [ganymedes01/TheErebus#586]
Minecraft 1.12.2
Erebus 1.0.19

Player was fighting a Crushroom, this caused a server crash. Replicated twice more. 

Partial log below:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  LoadingPlugin (Quark-r1.4-121.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-49.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Wizardry Plugin (wizardry-0.7.2.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.4-Anarchy.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.4.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/6/18 1:14 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at erebus.entity.EntitySporeBall.func_70184_a(EntitySporeBall.java:71)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at erebus.entity.EntitySporeBall.func_70071_h_(EntitySporeBall.java:42)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at erebus.entity.EntitySporeBall.func_70184_a(EntitySporeBall.java:71)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at erebus.entity.EntitySporeBall.func_70071_h_(EntitySporeBall.java:42)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: erebus:erebus.spore_ball (erebus.entity.EntitySporeBall)
	Entity ID: 20739
	Entity Name: entity.erebus.spore_ball.name
	Entity's Exact location: -328.10, 57.02, 39.06
	Entity's Block location: World: (-329,57,39), Chunk: (at 7,3,7 in -21,2; contains blocks -336,0,32 to -321,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.39, -0.47, -0.58
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['<USERNAME REDACTED>'/20736, l='world', x=-328.01, y=56.00, z=39.32]]
	Chunk stats: ServerChunkCache: 297 Drop: 0
	Level seed: -4525594095367697830
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by vadis365** [comment]
Will be fixed in the next release, was a client method being used where it shouldn't - doh!
New fix release will be up in a couple of days, closing due to it fixed in dev now.
Thanks for finding it out and reporting :)
