### ISSUE TITLE
Crash when eating any Erebus food if AppleCore is present

### ISSUE THREAD

**Issue by coledot** [ganymedes01/TheErebus#628]
Mod version 1.0.22

Foods from this mod appear to be incompatible with the AppleCore mod. If you eat any Erebus food (e.g. Raw Titan Chop), when AppleCore (v3.1.3) is loaded, the game crashes.

Given the location where the crash occurs (ItemErebusFood.java:81), I believe this may be closely related: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

Stacktrace:

java.lang.NullPointerException: Ticking player
    at net.minecraft.util.FoodStats.func_151686_a(SourceFile:32)
    at erebus.items.ItemErebusFood.func_77654_b(ItemErebusFood.java:81)
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222)
    at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2778)
    at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125)
    at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
 
Full crash log: https://pastebin.com/uBc5qySM

**Comment by vadis365** [comment]
Fixed in dev.
Closing as the next release will have this sorted.
