### ISSUE TITLE
Crash whenever placing the quake hammer into slot

### ISSUE THREAD

**Issue by Ooofball** [ganymedes01/TheErebus#632]
Whenever I place the quake hammer from the creative inventory into the currently selected hotbar slot, the game crashes.

Here is the crash report.

```
---- Minecraft Crash Report ----
// I blame vadis365, author of Erebus.

Time: 2018-08-20 03:31:59 MDT
Description: Unexpected error

java.lang.NullPointerException
    at erebus.client.gui.RenderWarHammerChargeBar.onRenderHUD(RenderWarHammerChargeBar.java:30)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_589_RenderWarHammerChargeBar_onRenderHUD_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:349)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:142)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1421)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Oofball'/80, l='MpServer', x=287.41, y=102.00, z=2194.48]]
  Chunk stats: MultiplayerChunkCache: 841, 841
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (676,4,1739), Chunk: (at 4,0,11 in 42,108; contains blocks 672,0,1728 to 687,255,1743), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
  Level time: 83477 game time, 142085 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 101 total; [EntityKidAngora['Angora Kid'/768, l='MpServer', x=248.50, y=102.00, z=2147.50], EntityStallionDraftHorse['Draft Horse Stallion'/514, l='MpServer', x=255.91, y=102.00, z=2229.36], EntityVillager['Villager'/259, l='MpServer', x=247.50, y=103.00, z=2161.30], EntityFoalDraftHorse['Draft Horse Foal'/515, l='MpServer', x=254.01, y=102.00, z=2229.98], EntityCalfFriesian['Friesian Calf'/771, l='MpServer', x=246.01, y=102.00, z=2150.08], EntityVillager['Villager'/261, l='MpServer', x=247.51, y=103.00, z=2187.91], EntityFoalDraftHorse['Draft Horse Foal'/517, l='MpServer', x=259.27, y=102.00, z=2224.81], EntityBullFriesian['Friesian Bull'/773, l='MpServer', x=243.64, y=102.00, z=2150.34], EntityVillager['Villager'/262, l='MpServer', x=255.49, y=103.00, z=2189.70], EntityCalfFriesian['Friesian Calf'/774, l='MpServer', x=245.05, y=102.00, z=2148.96], EntityVillager['Villager'/263, l='MpServer', x=240.66, y=103.00, z=2176.15], EntityVillager['Villager'/264, l='MpServer', x=240.49, y=103.00, z=2187.11], EntityBuckAngora['Angora Buck'/520, l='MpServer', x=255.23, y=102.00, z=2240.40], EntityBullFriesian['Friesian Bull'/776, l='MpServer', x=243.50, y=102.00, z=2148.50], EntityVillager['Villager'/265, l='MpServer', x=240.28, y=103.00, z=2175.30], EntityKidAngora['Angora Kid'/521, l='MpServer', x=258.68, y=102.00, z=2230.99], EntityCalfFriesian['Friesian Calf'/777, l='MpServer', x=243.50, y=102.00, z=2148.50], EntityChickLeghorn['Leghorn Chick'/522, l='MpServer', x=259.51, y=102.00, z=2221.85], EntityStallionDraftHorse['Draft Horse Stallion'/779, l='MpServer', x=253.50, y=102.00, z=2147.50], EntityRoosterLeghorn['Leghorn Rooster'/524, l='MpServer', x=255.69, y=102.00, z=2233.44], EntityFoalDraftHorse['Draft Horse Foal'/780, l='MpServer', x=253.50, y=102.00, z=2147.50], EntityVillager['Villager'/269, l='MpServer', x=225.57, y=103.00, z=2214.62], EntityChickLeghorn['Leghorn Chick'/525, l='MpServer', x=250.29, y=102.00, z=2232.42], EntityVillager['Villager'/270, l='MpServer', x=226.64, y=103.00, z=2223.86], EntityStallionDraftHorse['Draft Horse Stallion'/782, l='MpServer', x=250.50, y=102.00, z=2151.50], EntityVillager['Villager'/271, l='MpServer', x=224.30, y=103.00, z=2215.68], EntityFoalDraftHorse['Draft Horse Foal'/783, l='MpServer', x=250.50, y=102.00, z=2151.50], EntityVillager['Villager'/272, l='MpServer', x=224.74, y=103.00, z=2214.92], EntityVillager['Villager'/273, l='MpServer', x=226.46, y=103.00, z=2223.15], EntityRoosterLeghorn['Leghorn Rooster'/529, l='MpServer', x=262.22, y=102.00, z=2233.54], EntityVillager['Villager'/274, l='MpServer', x=249.30, y=103.00, z=2222.30], EntityVillager['Villager'/275, l='MpServer', x=259.42, y=103.00, z=2199.74], EntityChickLeghorn['Leghorn Chick'/531, l='MpServer', x=251.55, y=102.00, z=2230.87], EntityVillager['Villager'/276, l='MpServer', x=270.03, y=103.00, z=2192.36], EntityChickLeghorn['Leghorn Chick'/535, l='MpServer', x=251.49, y=102.00, z=2230.38], EntityRoosterLeghorn['Leghorn Rooster'/549, l='MpServer', x=289.30, y=102.00, z=2183.50], EntityHenLeghorn['Leghorn Hen'/550, l='MpServer', x=285.20, y=98.00, z=2193.20], EntityHenLeghorn['Leghorn Hen'/551, l='MpServer', x=279.50, y=102.00, z=2180.50], EntityHenLeghorn['Leghorn Hen'/552, l='MpServer', x=275.50, y=102.00, z=2177.50], EntityBullFriesian['Friesian Bull'/563, l='MpServer', x=349.82, y=102.00, z=2241.15], EntityBullFriesian['Friesian Bull'/569, l='MpServer', x=350.79, y=102.00, z=2239.37], EntityDartFrogs['Tree Frog'/329, l='MpServer', x=253.51, y=102.00, z=2176.77], EntityEweSuffolk['Suffolk Ewe'/331, l='MpServer', x=271.77, y=102.00, z=2178.51], EntityHogYorkshire['American Yorkshire Hog'/333, l='MpServer', x=263.65, y=102.00, z=2172.51], EntityRabbitDoeChinchilla['Chinchilla Doe'/336, l='MpServer', x=259.00, y=102.00, z=2157.86], EntityVillager['Villager'/81, l='MpServer', x=266.43, y=103.00, z=2213.50], EntityVillager['Villager'/82, l='MpServer', x=263.30, y=103.00, z=2221.99], EntityRabbitKitJack['Jack Kit'/338, l='MpServer', x=276.74, y=102.00, z=2176.04], EntityVillager['Villager'/83, l='MpServer', x=218.86, y=103.00, z=2192.53], EntityVillager['Villager'/84, l='MpServer', x=231.42, y=103.00, z=2199.51], EntityVillager['Villager'/86, l='MpServer', x=212.37, y=103.00, z=2162.33], EntityVillager['Villager'/87, l='MpServer', x=222.40, y=103.00, z=2157.06], EntityVillager['Villager'/88, l='MpServer', x=211.37, y=103.00, z=2163.32], EntityVillager['Villager'/89, l='MpServer', x=222.30, y=103.00, z=2158.53], EntityVillager['Villager'/90, l='MpServer', x=219.50, y=103.00, z=2191.81], EntityPlayerSP['Oofball'/80, l='MpServer', x=287.41, y=102.00, z=2194.48], EntitySnail['Snail'/378, l='MpServer', x=264.90, y=102.00, z=2170.36], EntityDeer['Deer'/386, l='MpServer', x=258.14, y=102.00, z=2159.08], EntityChickLeghorn['Leghorn Chick'/389, l='MpServer', x=307.71, y=102.00, z=2174.16], EntityRabbitBuckDutch['Dutch Buck'/391, l='MpServer', x=309.41, y=102.00, z=2155.57], EntityRabbitKitDutch['Dutch Kit'/392, l='MpServer', x=305.71, y=102.00, z=2157.83], EntityRabbitBuckDutch['Dutch Buck'/394, l='MpServer', x=314.93, y=102.00, z=2153.49], EntityRabbitBuckDutch['Dutch Buck'/396, l='MpServer', x=327.98, y=102.00, z=2166.36], EntityRabbitBuckDutch['Dutch Buck'/398, l='MpServer', x=328.72, y=102.00, z=2147.13], EntityRabbitKitDutch['Dutch Kit'/399, l='MpServer', x=301.41, y=102.00, z=2151.29], EntityRabbitBuckLop['Lop Buck'/401, l='MpServer', x=309.41, y=102.00, z=2165.54], EntityRabbitKitLop['Lop Kit'/403, l='MpServer', x=319.17, y=102.00, z=2162.95], EntityRabbitBuckLop['Lop Buck'/407, l='MpServer', x=307.46, y=102.00, z=2167.09], EntityStallionDraftHorse['Draft Horse Stallion'/666, l='MpServer', x=257.50, y=102.00, z=2155.50], EntityFoalDraftHorse['Draft Horse Foal'/667, l='MpServer', x=257.49, y=102.00, z=2155.49], EntityRabbitBuckLop['Lop Buck'/412, l='MpServer', x=297.99, y=102.00, z=2144.24], EntityStallionDraftHorse['Draft Horse Stallion'/669, l='MpServer', x=256.50, y=102.00, z=2153.50], EntityHenLeghorn['Leghorn Hen'/672, l='MpServer', x=261.55, y=102.00, z=2163.27], EntityRabbitDoeDutch['Dutch Doe'/417, l='MpServer', x=247.85, y=102.56, z=2153.96], EntityRabbitKitDutch['Dutch Kit'/419, l='MpServer', x=236.82, y=102.35, z=2140.20], EntityPigletYorkshire['American Yorkshire Piglet'/421, l='MpServer', x=253.93, y=102.00, z=2138.60], EntityHogYorkshire['American Yorkshire Hog'/423, l='MpServer', x=250.31, y=102.00, z=2144.86], EntityPigletYorkshire['American Yorkshire Piglet'/430, l='MpServer', x=248.56, y=102.00, z=2152.40], EntityBuckFainting['Fainting Buck'/433, l='MpServer', x=250.73, y=102.00, z=2146.94], EntityBuckFainting['Fainting Buck'/435, l='MpServer', x=247.92, y=102.00, z=2131.81], EntityKidFainting['Fainting Kid'/436, l='MpServer', x=251.76, y=102.00, z=2133.92], EntityBuckFainting['Fainting Buck'/438, l='MpServer', x=253.40, y=102.00, z=2135.15], EntityKidFainting['Fainting Kid'/439, l='MpServer', x=253.89, y=102.00, z=2136.34], EntityBuckFainting['Fainting Buck'/441, l='MpServer', x=246.87, y=102.00, z=2151.14], EntityKidFainting['Fainting Kid'/442, l='MpServer', x=256.46, y=102.00, z=2139.53], EntityRamFriesian['Friesian Ram'/463, l='MpServer', x=341.66, y=102.00, z=2216.15], EntityLambFriesian['Friesian Lamb'/464, l='MpServer', x=337.60, y=102.00, z=2225.31], EntityEweFriesian['Friesian Ewe'/465, l='MpServer', x=341.49, y=102.00, z=2219.30], EntityHorse['Horse'/466, l='MpServer', x=339.29, y=102.00, z=2218.37], EntityHorse['Horse'/467, l='MpServer', x=339.50, y=102.00, z=2215.50], EntityHorse['Horse'/468, l='MpServer', x=260.59, y=102.00, z=2163.00], EntityBuckAngora['Angora Buck'/470, l='MpServer', x=332.15, y=102.00, z=2228.80], EntityBuckAngora['Angora Buck'/472, l='MpServer', x=338.00, y=102.00, z=2222.00], EntityBuckAngora['Angora Buck'/475, l='MpServer', x=335.05, y=102.00, z=2228.96], EntityKidAngora['Angora Kid'/477, l='MpServer', x=349.43, y=102.00, z=2231.29], EntityHenLeghorn['Leghorn Hen'/744, l='MpServer', x=263.50, y=102.00, z=2140.50], EntityFoalDraftHorse['Draft Horse Foal'/745, l='MpServer', x=266.49, y=102.00, z=2134.49], EntityHogYorkshire['American Yorkshire Hog'/747, l='MpServer', x=265.83, y=102.00, z=2144.95], EntityHogYorkshire['American Yorkshire Hog'/749, l='MpServer', x=260.97, y=102.00, z=2150.84], EntityPigletYorkshire['American Yorkshire Piglet'/750, l='MpServer', x=260.27, y=102.00, z=2151.72], EntityVillager['Villager'/252, l='MpServer', x=263.75, y=103.00, z=2222.65]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1549007288 bytes (1477 MB) / 3625451520 bytes (3457 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xmn3G
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2757 Optifine OptiFine_1.12.2_HD_U_D1 74 mods loaded, 74 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                        | Version          | Source                                            | Signature                                |
       |:--------- |:------------------------- |:---------------- |:------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft                 | 1.12.2           | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | mcp                       | 9.42             | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | FML                       | 8.0.99.99        | forge-1.12.2-14.23.4.2757.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                     | 14.23.4.2757     | forge-1.12.2-14.23.4.2757.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | creativecoredummy         | 1.0.0            | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | itemphysic                | 1.4.0            | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | openmodscore              | 0.11.5           | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | foamfixcore               | 7.7.4            | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | obfuscate                 | 0.2.5            | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | srm-hooks                 | 1.12.2-1.0.0     | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | biomesoplenty             | 7.0.1.2399       | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar     | None                                     |
       | UCHIJAAAA | baubles                   | 1.5.2            | Baubles-1.12-1.5.2.jar                            | None                                     |
       | UCHIJAAAA | botania                   | r1.10-354        | Botania+r1.10-354.jar                             | None                                     |
       | UCHIJAAAA | craftstudioapi            | 1.0.0            | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
       | UCHIJAAAA | harvestcraft              | 1.12.2x          | Pam's+HarvestCraft+1.12.2x.jar                    | None                                     |
       | UCHIJAAAA | quark                     | r1.5-127         | Quark-r1.5-127.jar                                | None                                     |
       | UCHIJAAAA | animania                  | 1.5.1.1          | animania-1.12.2-1.5.1.1.jar                       | None                                     |
       | UCHIJAAAA | appliedenergistics2       | rv5-stable-11    | appliedenergistics2-rv5-stable-11.jar             | None                                     |
       | UCHIJAAAA | psi                       | r1.1-59          | Psi-r1.1-59.jar                                   | None                                     |
       | UCHIJAAAA | autoreglib                | 1.3-20           | AutoRegLib-1.3-20.jar                             | None                                     |
       | UCHIJAAAA | bullseye                  | 3.0.6            | Bullseye-1.12.2-3.0.6.jar                         | None                                     |
       | UCHIJAAAA | redstoneflux              | 2.0.2            | RedstoneFlux-1.12-2.0.2.3-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | car                       | 1.2.11           | car-1.2.11.jar                                    | None                                     |
       | UCHIJAAAA | cdm                       | 0.4.1            | cdm-0.4.1-mc1.12.2.jar                            | None                                     |
       | UCHIJAAAA | cfm                       | 5.6.0            | cfm-5.6.0-mc1.12.2.jar                            | None                                     |
       | UCHIJAAAA | charset                   | 0.5.5.1          | Charset-Lib-0.5.5.1.jar                           | None                                     |
       | UCHIJAAAA | codechickenlib            | 3.2.1.351        | CodeChickenLib-1.12.2-3.2.1.351-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | chickenchunks             | 2.4.1.73         | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | creativecore              | 1.9.9            | CreativeCore_v1.9.27_mc1.12.2.jar                 | None                                     |
       | UCHIJAAAA | customnpcs                | 1.12             | CustomNPCs_1.12.2(09jul18).jar                    | None                                     |
       | UCHIJAAAA | enderstorage              | 2.4.5.135        | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | erebus                    | 1.0.22           | Erebus-1.0.22.jar                                 | None                                     |
       | UCHIJAAAA | familiarfauna             | 1.0.10           | FamiliarFauna-1.12.2-1.0.10.jar                   | None                                     |
       | UCHIJAAAA | fbp                       | 2.4.0            | FancyBlockParticles-1.12.x-2.4.0.jar              | None                                     |
       | UCHIJAAAA | fastbench                 | 1.5.1            | FastWorkbench-1.12.2-1.5.1.jar                    | None                                     |
       | UCHIJAAAA | flansmod                  | 5.5.2            | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
       | UCHIJAAAA | flansmodapocalypse        | 1.0              | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
       | UCHIJAAAA | foamfix                   | 0.10.0-1.12.2    | foamfix-0.10.0-1.12.2.jar                         | None                                     |
       | UCHIJAAAA | forgemultipartcbe         | 2.5.0.71         | ForgeMultipart-1.12.2-2.5.0.71-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | microblockcbe             | 2.5.0.71         | ForgeMultipart-1.12.2-2.5.0.71-universal.jar      | None                                     |
       | UCHIJAAAA | minecraftmultipartcbe     | 2.5.0.71         | ForgeMultipart-1.12.2-2.5.0.71-universal.jar      | None                                     |
       | UCHIJAAAA | jei                       | 4.11.0.212       | jei_1.12.2-4.11.0.212.jar                         | None                                     |
       | UCHIJAAAA | malisiscore               | 1.12.2-6.4.0     | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
       | UCHIJAAAA | malisisdoors              | 1.12.2-7.3.0     | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
       | UCHIJAAAA | mantle                    | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                          | None                                     |
       | UCHIJAAAA | mrtjpcore                 | 2.1.3.35         | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
       | UCHIJAAAA | neat                      | 1.4-17           | Neat+1.4-17.jar                                   | None                                     |
       | UCHIJAAAA | nei                       | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.238-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | openmods                  | 0.11.5           | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | openblocks                | 1.7.6            | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | projectred-core           | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
       | UCHIJAAAA | projectred-compat         | 1.0              | ProjectRed-1.12.2-4.9.1.92-compat.jar             | None                                     |
       | UCHIJAAAA | projectred-integration    | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
       | UCHIJAAAA | projectred-transmission   | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
       | UCHIJAAAA | projectred-fabrication    | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
       | UCHIJAAAA | projectred-illumination   | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-lighting.jar           | None                                     |
       | UCHIJAAAA | projectred-expansion      | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
       | UCHIJAAAA | projectred-relocation     | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
       | UCHIJAAAA | projectred-transportation | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
       | UCHIJAAAA | projectred-exploration    | 4.9.1.92         | ProjectRed-1.12.2-4.9.1.92-world.jar              | None                                     |
       | UCHIJAAAA | pdp                       | 1.12.2-1.1.0     | ProportionalDestructionParticles-1.12.2-1.1.0.jar | None                                     |
       | UCHIJAAAA | redstonepaste             | 1.7.5            | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | UCHIJAAAA | secretroomsmod            | 5.6.4            | secretroomsmod-1.12.2-5.6.4.jar                   | None                                     |
       | UCHIJAAAA | sereneseasons             | 1.2.6            | SereneSeasons-1.12.2-1.2.6-universal.jar          | None                                     |
       | UCHIJAAAA | sharpbone                 | 1.0              | SharpBone-1.12.2-1.0.jar                          | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UCHIJAAAA | tconstruct                | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87.jar                   | None                                     |
       | UCHIJAAAA | translocators             | 2.5.1.77         | Translocators-1.12.2-2.5.1.77-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | bspkrscore                | at_0.9           | Treecapitator-1.12-at_0.9a.jar                    | None                                     |
       | UCHIJAAAA | treecapitator             | at_0.9           | Treecapitator-1.12-at_0.9a.jar                    | None                                     |
       | UCHIJAAAA | vanillafix                | 1.0.9-97         | VanillaFix-1.0.9-97.jar                           | None                                     |
       | UCHIJAAAA | vehicle                   | 0.21.0           | vehicle-0.21.0-mc1.12.2.jar                       | None                                     |
       | UCHIJAAAA | wearablebackpacks         | 3.1.3            | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
       | UCHIJAAAA | worldedit                 | 6.1.8            | worldedit-forge-mc1.12-6.1.8-dist.jar             | None                                     |
       | UCHIJAAAA | wrcbe                     | 2.3.1            | WR-CBE-1.12.2-2.3.1.29-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
  Loaded coremods (and transformers): Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.0-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.9.27_mc1.12.2.jar)
                                        
                                      LoadingPlugin (Quark-r1.5-127.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                        openmods.core.OpenModsClassTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.16_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      IonChests (IonChests-1.0.0.jar)
                                        pl.asie.ionchests.IonChestsTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
  Suspected Mods: Erebus (erebus)
  Launched Version: 1.12.2-forge1.12.2-14.23.4.2757
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
```

**Comment by vadis365** [comment]
Yeah this is because the NBT isn't set on the quake hammer if you cheat it in. I'll change it so it can be selected from the creative menu in the next version - thanks for the report. :)
