### ISSUE TITLE
hoppers crash trying to insert items into a full bamboo crate

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#660]
Spread some stone over the entirety of the crate, hopper in a sword, boom. This is with the single-block crate, and the hopper pointing into the side. Well, with a BL syrmonomite hopper anyways. And also diet hoppers is installed.

```
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.tileentity.TileEntityHopper.func_174919_a(TileEntityHopper.java:240)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:205)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vadis365** [comment]
Hello,
Fixed in dev. Will be sorted next update.
Cheers,
Me.
