### ISSUE TITLE
Server crash when trying to hopper items into a composter

### ISSUE THREAD

**Issue by praecipitator** [ganymedes01/TheErebus#687]
Title says it all. Attaching a hopper to a composter and putting items into the hopper causes a server crash as soon as the chunk is loaded.

The log file isn't very helpful, but here it is:
```
19:39:58] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.tileentity.TileEntityHopper.func_174919_a(TileEntityHopper.java:240) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:205) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122) ~[avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
```

Edit: additional infos: the hopper was attached to the side of the composter and contained dead bushes. The composter was running on non-cultivated mould and was processing pink tulips.

**Comment by vadis365** [comment]
Hello,
I'll take a look - thanks for the report.
Cheers,
Me.

**Comment by vadis365** [comment]
fixed in dev
