### ISSUE TITLE
Breaking Preserved Amber block in Multiplayer causes client disconnect.

### ISSUE THREAD

**Issue by katubug** [ganymedes01/TheErebus#753]
* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.5](http://enthusiasticraft.cf/modpack-update-1-7-5/#modlist)
* **Mod versions:** Erebus-1.0.30

Hello! I recently added your mod to my pack and server. My players and I went to go do some exploring, and I happened upon some Amber, which I veinmined. There was a block left behind - a Preserved Amber. I mined it, and right as the block would have broken, I was disconnected from the server. The server itself seemed fine.

I received this crash report: https://paste.dimdev.org/wuxufeboco.mccrash

I also went back and found this in my latest.log (it's just an excerpt, let me know if you need more): https://pastebin.com/vjf0q4pw

After I reconnected, the block was still there in the world. I went into creative and used pick-block on it, then broke it via left click. I did not disconnect. I did `/ct hand` to get the NBT data of the item, since the crash mentioned NBT tags. Here it is:

```
<erebus:preserved_block>.withTag({EntityNBT: {Motion: [0.0, 0.0, 0.0], UUIDLeast: -9123975985058953188 as long, Health: 5 as short, RelativeAABB: [-0.125, 0.0, -0.125, 0.125, 0.25, 0.125], Invulnerable: 0 as byte, Air: 300 as short, OnGround: 0 as byte, Dimension: 66, PortalCooldown: 0, Rotation: [0.0 as float, 0.0 as float], UpdateBlocked: 0 as byte, FallDistance: 0.0 as float, Item: {ForgeCaps: {"astralsorcery:cap_item_amulet_holder": {}}, id: "erebus:wand_of_preservation", Count: 1 as byte, Damage: 0 as short}, UUIDMost: 6770730859922343921 as long, Pos: [718.0, 32.0, 691.0], PickupDelay: 0 as short, Fire: -1 as short, ForgeCaps: {"llibrary:extendedentitydatacapability": {}}, id: "minecraft:item", Lifespan: 6000, Age: 0 as short}})
```

Thank you for your time, and the excellent mod! Please let me know if you need any other information. :)

**Comment by katubug** [comment]
An additional note - I went to see if I could replicate the crash, so I went back into survival and placed the block. As soon as I did, I got the same crash: https://paste.dimdev.org/qewuyuzupa.mccrash

Edit: this does not appear to be an issue with the preserved amber containing spiders, according to one of my players.

**Comment by fatcatgamer123** [comment]
i had the same issue with the crash.

**Comment by Psifour** [comment]
This issue has impacted a server I am playing on. As such I am going to fix it and submit a PR. Can I get that error report from your original issue? @katubug 

My initial assumption is that this is an interaction issue with another mod that is expecting additional information (WAILA/HWYLA) that is not present in the NBT data. This is assumed by there also being an associated crash from those mods when placing an amber block.

**Comment by katubug** [comment]
Hi, I'm not sure I still have a copy of that report, because I think Oct of
last year was when I was still on my old pc which I no longer have access
to. My apologies.

**Comment by dimomite** [comment]
Hi. I thinks I experienced same issue. Callstack is provided, will it be enough?
`java.lang.IllegalArgumentException: Invalid null NBT value with key EntityNBT
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at erebus.blocks.BlockPreservedBlock.getPickBlock(BlockPreservedBlock.java:142)
	at mcjty.theoneprobe.rendering.OverlayRenderer.requestBlockInfo(OverlayRenderer.java:326)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:252)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2138_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by quietust** [comment]
I've encountered the "crash upon placing amber preservaion block" multiple times in Project Ozone 3, but I just found that disabling Hwyla (by pressing 1 on the numpad) immediately before placing the block seems to prevent the crash.

**Comment by DocCyblade** [comment]
Having the same issue on our server as well. However it seems to be with The One Probe. Local game with only those two mods and it does the same thing with the same error/crash. Remove the TOP mod and it works.
