### ISSUE TITLE
I'm trying to make a mod pack but when i try to load in the world, I get this issue

### ISSUE THREAD

**Issue by TRM2002** [ganymedes01/TheErebus#757]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/1/20 10:36 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:855)
	at net.minecraft.world.World.func_72838_d(World.java:1338)
	at net.minecraft.block.Block.func_149642_a(Block.java:683)
	at net.minecraft.block.Block.func_149690_a(Block.java:662)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.BlockDynamicLiquid.func_149813_h(SourceFile:115)
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(SourceFile:102)
	at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:432)
	at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:409)
	at net.minecraft.block.BlockDynamicLiquid.func_149726_b(SourceFile:225)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.block.BlockDynamicLiquid.func_149813_h(SourceFile:117)
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(SourceFile:102)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_76484_a(SourceFile:39)
	at biomesoplenty.common.world.generation.ForcedWorldFeatureBOP.generate(ForcedWorldFeatureBOP.java:20)
	at biomesoplenty.common.world.forcedgenerators.SpringForcedGenerator.setupGeneration(SpringForcedGenerator.java:28)
	at biomesoplenty.api.biome.BOPBiomeDecorator.func_150513_a(BOPBiomeDecorator.java:82)
	at biomesoplenty.api.biome.BOPBiomeDecorator.func_150512_a(BOPBiomeDecorator.java:50)
	at biomesoplenty.api.biome.BOPInheritedBiome.func_76728_a(BOPInheritedBiome.java:43)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:421)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:41)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at WorldServerOF.func_72963_a(WorldServerOF.java:80)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:855)
	at net.minecraft.world.World.func_72838_d(World.java:1338)
	at net.minecraft.block.Block.func_149642_a(Block.java:683)
	at net.minecraft.block.Block.func_149690_a(Block.java:662)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.BlockDynamicLiquid.func_149813_h(SourceFile:115)
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(SourceFile:102)
	at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:432)
	at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:409)
	at net.minecraft.block.BlockDynamicLiquid.func_149726_b(SourceFile:225)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.block.BlockDynamicLiquid.func_149813_h(SourceFile:117)
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(SourceFile:102)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_76484_a(SourceFile:39)
	at biomesoplenty.common.world.generation.ForcedWorldFeatureBOP.generate(ForcedWorldFeatureBOP.java:20)
	at biomesoplenty.common.world.forcedgenerators.SpringForcedGenerator.setupGeneration(SpringForcedGenerator.java:28)
	at biomesoplenty.api.biome.BOPBiomeDecorator.func_150513_a(BOPBiomeDecorator.java:82)
	at biomesoplenty.api.biome.BOPBiomeDecorator.func_150512_a(BOPBiomeDecorator.java:50)
	at biomesoplenty.api.biome.BOPInheritedBiome.func_76728_a(BOPInheritedBiome.java:43)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:421)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (66,64,360), Chunk: (at 2,4,8 in 4,22; contains blocks 64,0,352 to 79,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:41)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at WorldServerOF.func_72963_a(WorldServerOF.java:80)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 38 Drop: 0
	Level seed: -85186617942763995
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 950119320 bytes (906 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAAAAA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAAAAA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAAAAA	bspkrsCore{6.16} [bspkrsCore] (BspkrsCore-1.7.10.jar) 
	UCHIJAAAAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks+MoCreatures+Mod+v6.3.1.zip) 
	UCHIJAAAAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete+1.13.0.5+[1.7.10].jar) 
	UCHIJAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal (1).jar) 
	UCHIJAAAAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJAAAAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAAAAA	mw{1.11.7.7} [Modern Warfare] (mw-1.11.7.7_mc1.7.10.jar) 
	UCHIJAAAAAAA	necromancy{1.7.2} [Necromancy] (Necromancy-1.7.10.jar) 
	UCHIJAAAAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) 
	UCHIJAAAAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAAAAA	telepads{1.0.0} [Telepads] (Telepads+1.7.10+Full+Release+3.1.jar) 
	UCHIJAAAAAAA	Treecapitator{1.7.10} [Treecapitator] (Tree-Capitator-Mod-1.7.10.jar) 
	UCHIJAAAAAAA	VeinMiner{0.35.2_1.7.10-e134bd4} [Vein Miner] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UCHIJAAAAAAA	VeinMinerModSupport{0.35.2_1.7.10-e134bd4} [Mod Support] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UCHIJAAAAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAAAAA	xaerominimap{1.19.4} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Vortetty** [comment]
this does not appear to be the Erebus mod causing problems, as your error shows the Biomes O' Plenty mod attempting to decorate the landscape then Minecraft crashing from something with world generation.
