### ISSUE TITLE
[MC 1.12.2] - Server crash when placing Amber Preservation Block

### ISSUE THREAD

**Issue by Pdan4** [ganymedes01/TheErebus#764]
[Log here](https://paste.dimdev.org/oyerufobek.mccrash)

**Comment by fatcatgamer123** [comment]
this is an issue with waila, I've had this problem too.

**Comment by Psifour** [comment]
Please post logs with a proper pasting utility. Your current host does not keep these logs accessible long-term which makes them useless for diagnosing the problem when a developer eventually is interested in it.

**Comment by AdvancedWipe** [comment]
I'm not quite sure if this issue has been fixed, but I encountered the same problem described above. I am using the erebus version 1.12.2 1.0.31. But the error message is still the same as in the 1.12.2 1.0.30 version of erebus in the issue #753. If it is fixed in newer versions it's fine, if not here are my client crashreports and server crashreports. My server crashed, as well as my client. So its not off topic.

Server crash report:


Description: Exception ticking world

java.lang.IllegalArgumentException: Invalid null NBT value with key EntityNBT
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at erebus.tileentity.TileEntityPreservedBlock.func_189515_b(TileEntityPreservedBlock.java:69)
	at erebus.tileentity.TileEntityPreservedBlock.func_189518_D_(TileEntityPreservedBlock.java:41)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at erebus.tileentity.TileEntityPreservedBlock.func_189515_b(TileEntityPreservedBlock.java:69)
	at erebus.tileentity.TileEntityPreservedBlock.func_189518_D_(TileEntityPreservedBlock.java:41)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)


Client crashreport:

Description: Unexpected error

java.lang.IllegalArgumentException: Invalid null NBT value with key EntityNBT
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at erebus.blocks.BlockPreservedBlock.getPickBlock(BlockPreservedBlock.java:142)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:61)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_176_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Thread: Client thread
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at erebus.blocks.BlockPreservedBlock.getPickBlock(BlockPreservedBlock.java:142)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:61)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_176_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

**Comment by minnie1089** [comment]
I also experienced this issue.
[This](https://docs.google.com/document/d/1N4-qZk8XYxONUuzjn5w5Ryufr4fTXtHlPtjhq-GHuUg/edit?usp=sharing) is the log file post crash.
I don't know if this will be useful or not, but I placed the Antlion Overlord amber preservation block
